version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18  # Change this based on your application requirement
  build:
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm run build
artifacts:
  files:
    - '**/*'

